name: Home Assistant Webserver
version: "1.0.0"
slug: ha-webserver
description: A custom webserver addon for Home Assistant.
startup: services
boot: auto
arch:
  - amd64
  - armv7
  - aarch64
map:
  - config:rw
  - ssl:ro
  - www:rw
  - data:rw
ingress: true
ingress_port: 8080
panel_icon: mdi:web
panel_title: Webserver
options: {}
schema: {}
